Buffetiser_Unchained/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('buffetiser_main.urls'))
]

buffetiser_main/urls.py
from django.urls import path
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin', admin.site.urls),

    path('', views.main, name='Buffetiser'),
    path('<symbol>/', views.investmentDetails, name='Investment Details'),
    path('purchase', views.newPurchase, name='New Purchase'),
    path('add_purchase', views.addPurchase, name='Add Purchase'),
    path('config', views.config, name='Buffetiser Config'),
    path('live', views.updateLivePrices, name='Live Prices'),
    path('buffetiserHelp', views.buffetiserHelp, name='Buffetiser Help'),
]

buffetiser_main/models.py
from sqlite3 import Date

from django.db import models

from buffetiser_main.python.data_structures import Constants


class Investment(models.Model):
    """
    This represents either Shares or Crypto-currency. There is only one of these, of each type:platform:symbol
    in the system.
    Each one of these however, can have multiple purchases and sales.
    PK: symbol (+ exchange- would like to but can't yet. Don't know how).
    """
    investment_type = models.CharField(choices=Constants.InvestmentType.choices,
                                       max_length=20,
                                       default=Constants.InvestmentType.SHARES)
    name = models.CharField(max_length=200, default='unnamed')
    symbol = models.CharField(max_length=5, default='none', primary_key=True)
    currency = models.CharField(max_length=5, default='AUD')
    exchange = models.CharField(choices=Constants.Exchanges.choices,
                                max_length=4,
                                default=Constants.Exchanges.XASX)
    platform = models.CharField(choices=Constants.Platforms.choices,
                                max_length=255,
                                default=Constants.Platforms.CMC)

    unitsHeld = models.FloatField(default=0)                            # can handle shares (int) and crypto (float)
    totalFees = models.FloatField(default=0)                            # should only really be dollars/cents.
    averageCost = models.FloatField(default=0)
    totalCost = models.FloatField(default=0)
    livePrice = models.FloatField(default=0)
    totalValue = models.FloatField(default=0)
    profit = models.FloatField(default=0)
    percentProfit = models.FloatField(default=0)
    plotPath = models.CharField(max_length=512, default='./')      # hold the path of the last history plot.


class Purchase(models.Model):
    """
    """

    units = models.FloatField()
    price = models.FloatField()
    fee = models.FloatField()
    date = models.DateField()

    investment = models.ForeignKey(to=Investment, on_delete=models.CASCADE)


class Sale(models.Model):
    """
    """
    units = models.FloatField()
    price = models.FloatField()
    fee = models.FloatField()
    date = models.DateField()

    investment = models.ForeignKey(to=Investment, on_delete=models.CASCADE)


class History(models.Model):
    """
    """
    date = models.DateField(Date.today())
    open = models.FloatField(default=0)
    high = models.FloatField(default=0)
    low = models.FloatField(default=0)
    close = models.FloatField(default=0)
    adjustedClose = models.FloatField(default=0)
    volume = models.IntegerField(default=0)

    investment = models.ForeignKey(to=Investment, on_delete=models.CASCADE)

buffetiser_main/views.py
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from buffetiser_main.models import Purchase, Investment, History
from .python.data_structures import Constants
from .python.individual_investment_calculators import IndividualInvestmentCalculators
from .python.network import useBigCharts
from .python.bottom_line_calculators import BottomLineCalculators

import logging

# I added this line

# Create and configure logger
from .python.plots import plotPriceHistory

logging.basicConfig(filename="debug.log",
                    # format='%(asctime)s %(message)s',
                    format='----------Views--------%(message)s',
                    filemode='w')
# Creating an object
logger = logging.getLogger()
# Setting the threshold of logger to DEBUG
logger.setLevel(logging.DEBUG)


def main(request):
    """

    """
    investment_list = Investment.objects.order_by('symbol')  # [:5] #if investment_list else []
    # calculate totals for all investments
    calculator = BottomLineCalculators(investment_list)
    bottomLineCost = calculator.bottomLineCost()
    bottomLineValue = calculator.bottomLineValue()
    bottomLineProfit = calculator.bottomLineProfit()
    bottomLineProfitPercent = calculator.bottomLineProfitPercent()

    context = {'investment_list': investment_list,
               'bottom_line_cost': bottomLineCost,
               'bottom_line_value': bottomLineValue,
               'bottom_line_profit': bottomLineProfit,
               'bottom_line_profit_percent': bottomLineProfitPercent}

    return render(request, 'buffetiser_main/index.html', context)


def config(request):
    text = "<h1>Buffetiser Unchained Config!</h1>"
    return HttpResponse(text)


def buffetiserHelp(request):
    text = "<h1>Buffetiser Unchained Help!</h1>"
    return HttpResponse(text)


def investmentDetails(request, symbol):
    investment = get_object_or_404(Investment, pk=symbol)
    return render(request, 'buffetiser_main/investment_details.html', {'investment': investment})


def newPurchase(request):
    constants = Constants()
    investment_list = [Investment.objects.all()]
    context = {'constants': constants,
               'investment_list': investment_list}
    return render(request, 'buffetiser_main/new_purchase.html', context)


def addPurchase(request):
    """
    Add a new record of an investment purchase.
    """
    today = datetime.today()
    todayString = '{}-{}-{}'.format(today.year, today.month, today.strftime("%d"))

    # Pull data entered into Purchase form
    investment_type = request.POST.get('type', '---')
    symbol = request.POST.get('symbol', '---')
    name = request.POST.get('name', '---')
    exchange = request.POST.get('exchange', '---')
    platform = request.POST.get('platform', '---')
    currency = request.POST.get('currency', '---')
    units = int(request.POST.get('units', '---'))
    price = float(request.POST.get('price', '---'))
    fee = float(request.POST.get('fee', '---'))
    date = request.POST.get('date', '---')

    # If the investment (symbol) already exists, append additional data. Otherwise, create a new Investment.
    investment, investmentCreated = Investment.objects.get_or_create(symbol=symbol)

    # If it's a new Investment, start adding basic data.
    if investmentCreated:
        investment.investment_type = investment_type
        investment.name = name
        investment.exchange = exchange
        investment.platform = platform
        investment.currency = currency

    # If it's new or existing Investment, add details of the new Purchase.
    unitsHeld = int(units) + investment.unitsHeld
    totalFees = float(fee) + investment.totalFees
    totalCost = float((unitsHeld * price) + totalFees) + investment.totalCost
    averageCost = float(totalCost / unitsHeld)

    # Now we need the live price so we can calculate the final fields.
    getInvestmentData('useBigCharts', investment, todayString)

    totalValue = float((unitsHeld * investment.livePrice))
    profit = float((totalValue - totalCost))
    percentProfit = float((profit / totalCost) * 100)

    # Add all the new data to the Investment object and save to DB.
    investment.unitsHeld = unitsHeld
    investment.totalFees = totalFees
    investment.totalCost = totalCost
    investment.averageCost = averageCost
    investment.totalValue = totalValue
    investment.profit = profit
    investment.percentProfit = percentProfit
    investment.save()

    purchase = Purchase(units=units,
                        price=price,
                        fee=fee,
                        date=date,
                        investment=investment)

    purchase.save()

    return redirect('/')


def updateLivePrices(request):
    """
    Update the day values for each investment
    """
    # TODO: this should only happen once a day to stop us from hammering the service provider
    today = datetime.today()
    todayString = '{}-{}-{}'.format(today.year, today.month, today.strftime("%d"))

    for investment in Investment.objects.all():
        getInvestmentData('useBigCharts', investment, todayString)

    return redirect('/')


def getInvestmentData(service, investment, todayString):
    """

    """
    if service == 'useBigCharts':
        investmentData = useBigCharts(investment.symbol, todayString)

    historyObject = History(date=investmentData.get('date'),
                            open=investmentData.get('open'),
                            high=investmentData.get('high'),
                            low=investmentData.get('low'),
                            close=investmentData.get('close'),
                            adjustedClose=investmentData.get('adjustedClose'),
                            volume=investmentData.get('volume'),
                            investment=investment)

    historyObject.save()

    # TODO: does this have to be done???
    investment.livePrice = investmentData.get('close')
    calculator = IndividualInvestmentCalculators(investment)
    calculator.assignDayValue()
    calculator.assignTotalCost()
    calculator.assignTotalValue()
    calculator.assignTotalProfit()
    calculator.assignTotalProfitPercent()

    # add plot path
    investment.plotPath = plotPriceHistory(investment)

    investment.save()

buffetiser_main/templates/buffetiser_main/index.html
<!DOCTYPE html>
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'buffetiser_main/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'buffetiser_main/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'buffetiser_main/w3.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'buffetiser_main/bootstrap-5.0.2/css/bootstrap.css' %}">
    <link rel="shortcut icon" type="image/jpg" href="{% static 'buffetiser_main/img/icon.png' %}"/>
    <script src="{% static 'buffetiser_main/bootstrap-5.0.2/js/bootstrap.js' %}"></script>
    <script src="{% static 'buffetiser_main/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'buffetiser_main/scripts.js' %}"></script>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Buffetiser Unchained</title>
    </head>
    <body>
        <div id="left">
            {% load static %}
            <img id="icon" src="{% static 'buffetiser_main/img/icon.png' %}">
            <a href="/admin"><button class="w3-btn w3-round">Admin</button></a>
            <a href="/help"><button class="w3-btn w3-round">Help</button></a>
            <a href="/config"><button class="w3-btn w3-round">Config</button></a>
            <a href="/live"><button class="w3-btn w3-round">Live</button></a>
            <a href="/purchase"><button class="w3-btn w3-round">Purchase</button></a>
            <a href="/config"><button class="w3-btn w3-round">Sale</button></a>
            <a href="/config"><button class="w3-btn w3-round">Quit</button></a>
        </div>
        <div id="right">
            <div id="top">
                {% if investment_list %}
                    {% for investment in investment_list %}
                        <a class="btn btn-primary panel-title"
                            data-bs-toggle="collapse"
                            href="#{{ investment.symbol }}"
                            role="button"
                            aria-expanded="false"
                            aria-controls="collapseExample">
                            <label style="float: left">
                                {{ investment.name }} ({{ investment.symbol }})
                            </label>
                            <label style="text-align: left; width: 150px; float: right; padding-right: 30px" class="profit_colour_{{ investment.symbol }}">
                                P&L%: {{ investment.percentProfit|stringformat:'.2f' }}%
                            </label>
                            <label style="text-align: left; width: 150px; float: right; padding-right: 30px" class="profit_colour_{{ investment.symbol }}">
                                Day: ${{ investment.profit|stringformat:'.2f' }}
                            </label>
                        </a>
                        <div class="collapse" id={{ investment.symbol }}>
                            <div class="card card-body" id="panel-container">
                                <div class="panel-body">
                                    {% load static %}
                                    <div >
                                        <div id="top-inner-left">
                                            {% load static %}
                                            <img class="graph" src="{% static investment.plotPath %}">
                                        </div>
                                        <div id="top-inner-right">
                                            <table class="summary-table">
                                                <tr><td>Average Cost</td><td>${{ investment.averageCost|stringformat:'.2f' }}</td></tr>
                                                <tr><td>Units Held</td><td>{{ investment.unitsHeld|stringformat:'d' }}</td></tr>
                                                <tr><td>Total Cost</td><td>${{ investment.totalCost|stringformat:'.2f' }}</td></tr>
                                                <tr><td>Live Price</td><td>${{ investment.livePrice }}</td></tr>
                                                <tr><td>Value</td><td>${{ investment.totalValue|stringformat:'.2f' }}</td></tr>
                                                <tr><td>Profit</td><td><label class="profit_colour_{{ investment.symbol }} profit_text_{{ investment.symbol }}"></label></td></tr>
                                                <tr><td>      </td><td><label class="profit_colour_{{ investment.symbol }}">{{ investment.percentProfit|stringformat:'.2f' }}%</label></td></tr>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Script sets text color and text based on investment profit (positive/negative) -->
                        <script>
                            profit = Number(`{{ investment.profit }}`);
                            if (profit === 0) {
                                $(".profit_colour_{{ investment.symbol }}").css("color", "white");
                                profitText = "$" + Math.abs(Number(profit.toFixed(2)));
                                $(".profit_text_{{ investment.symbol }}").text(profitText);
                            }
                            else if (profit < 0) {
                                $(".profit_colour_{{ investment.symbol }}").css("color", "#FF7777");
                                profitText = "-$" + Math.abs(Number(profit.toFixed(2)));
                                $(".profit_text_{{ investment.symbol }}").text(profitText);
                            }
                            else {
                                $(".profit_colour_{{ investment.symbol }}").css("color", "#55FF55");
                                profitText = "$" + Math.abs(Number(profit.toFixed(2)));
                                $(".profit_text_{{ investment.symbol }}").text(profitText);
                            }
                        </script>
                    {% endfor %}
                {% else %}
                    <p>No investments are available.</p>
                {% endif %}
            </div>
            <div id="bottom">
                <div id="bottom-inner-left">
                    {% load static %}
                    <img class="graph" src="{% static 'buffetiser_main/img/summary.png' %}">
                </div>
                <div id="bottom-inner-right">
                    <table class="summary-table">
                        <tr><td>Cost</td><td>${{ bottom_line_cost }}</td></tr>
                        <tr><td>Value</td><td>${{ bottom_line_value }}</td></tr>
                        <tr><td>Day</td><td>$100</td></tr>
                        <tr><td>Profit</td><td class="totals">${{ bottom_line_profit|stringformat:'.2f' }}</td></tr>
                        <tr><td></td><td class="totals">{{ bottom_line_profit_percent|stringformat:'.2f' }}%</td></tr>
                    </table>
                </div>
                <!-- Script sets text color based on investment profit (positive/negative) -->
                <script>
                    profit = Number(`{{ bottom_line_profit }}`);
                    if (profit === 0) {
                        $(".totals").css("color", "white");
                    }
                    else if (profit < 0) {
                        $(".totals").css("color", "#FF7777");
                    }
                    else if (profit > 0) {
                        $(".totals").css("color", "#55FF55");
                    }
                </script>
            </div>
        </div>
    </body>
</html>

buffetiser_main/templates/buffetiser_main/investment_details.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body class="investmentDetails">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'buffetiser_main/style.css' %}">

        <h1>Investment</h1>
        <h3>{{ investment.symbol }}</h3>
        <h3>{{ investment.name }}</h3>
        <h3>{{ investment.type }}</h3>
        <h3>{{ investment.exchange }}</h3>
        <h3>{{ investment.platform }}</h3>
        <h3>{{ investment.currency }}</h3>
        <hr>
        <h1>Purchases</h1>
        {% for purchase in investment.purchase_set.all %}
            <h3>{{ purchase.units }}</h3>
            <h3>{{ purchase.price }}</h3>
            <h3>{{ purchase.fee }}</h3>
            <h3>{{ purchase.date }}</h3>
        {% endfor %}




    </body>
</html>

buffetiser_main/templates/buffetiser_main/new_purchase.html
<!DOCTYPE html>
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'buffetiser_main/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'buffetiser_main/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'buffetiser_main/w3.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'buffetiser_main/bootstrap-5.0.2/css/bootstrap.css' %}">
    <link rel="shortcut icon" type="image/jpg" href="{% static 'buffetiser_main/img/icon.png' %}"/>
    <script src="{% static 'buffetiser_main/bootstrap-5.0.2/js/bootstrap.js' %}"></script>
    <script src="{% static 'buffetiser_main/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'buffetiser_main/scripts.js' %}"></script>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>New Purchase</title>
    </head>
    <body class="new_purchase">
        <div class="w3-card-4">
            <div class="w3-container">
              <h2>Add New Investment Purchase</h2>
            </div>
            <div>
                <form class="w3-container" action="add_purchase" method="post">
                {% csrf_token %}
                <fieldset>
                    <label>From Existing Investment</label>
                    <select class="w3-select" id="previous">
                        <option value="" disabled selected>Choose your option</option>
                        {% if investment_list %}
                            {% for investment in investment_list %}
                                <option value={{ investment.symbol }}>{{ investment.name }} ({{ investment.symbol }})</option>
                            {% endfor %}
                        {%  endif %}
                    </select>
                    <script>
                        // This automatically fills in information about a held investment to save time.
                        $('select').on('change', function() {
                            {% for investment in investment_list %}
                                if ($("#previous").val() == `{{ investment.symbol }}`) {
                                    $("#type").val(`{{ investment.investment_type }}`).change()
                                    $("#symbol").val(`{{ investment.symbol }}`)
                                    $("#name").val(`{{ investment.name }}`)
                                    $("#exchange").val(`{{ investment.exchange }}`).change();
                                    $("#platform").val(`{{ investment.platform }}`).change();
                                    $("#currency").val(`{{ investment.currency }}`).change();
                                }
                            {% endfor %}
                        });
                    </script>
                    <hr>
                    <label>Type</label>
                    <select class="w3-select" name="type" id="type">
                      <option value="" disabled selected>Choose your option</option>
                        {% for t in constants.InvestmentType.choices %}
                            <option id="type" name="type" value={{ t.0 }}>{{ t.1 }}</option>
                        {% endfor %}
                    </select>
                    <label>Symbol</label><input type="text" class="w3-input" id="symbol" name="symbol" required>
                    <label>Name</label><input type="text" class="w3-input" id="name" name="name" required>
                    <label>Exchange</label>
                    <select class="w3-select" name="exchange" id="exchange">
                      <option value="" disabled selected>Choose your option</option>
                        {% for t in constants.Exchanges.choices %}
                            <option id="exchange" name="exchange" value={{ t.0 }}>{{ t.1 }}</option>
                        {% endfor %}
                    </select>
                    <label>Platform</label>
                    <select class="w3-select" name="platform" id="platform">
                      <option value="" disabled selected>Choose your option</option>
                        {% for t in constants.Platforms.choices %}
                            <option id="platform" name="platform" value={{ t.0 }}>{{ t.1 }}</option>
                        {% endfor %}
                    </select>
                    <label>Currency</label>
                    <select class="w3-select" name="currency" id="currency">
                      <option value="" disabled selected>Choose your option</option>
                        {% for t in constants.Currencies.choices %}
                            <option id="currency" name="currency" value={{ t.0 }}>{{ t.1 }}</option>
                        {% endfor %}
                    </select>
                    <label>Units</label><input type="text" class="w3-input" id="units" name="units" required>
                    <label>Price</label><input type="text" class="w3-input" id="price" name="price" required>
                    <label>Fee</label><input type="text" class="w3-input" id="fee" name="fee" required>
                    <label>Date</label><input type="date" class="w3-input" id="date" name="date" required>

                    <button type="submit" class="submit-btn w3-btn w3-round">Add</button>
                </fieldset>
                </form>
            </div>
        </div>
    </body>
</html>